site_name: Madeline
copyright: Copyright &copy; 2021 - present, MatthewSoft
repo_url: https://github.com/madeline-bot/docs-v2
repo_name: madeline-bot/docs-v2
edit_uri: edit/master/docs/
theme:
  name: material
  favicon: images/favicon.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.share
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/book
extra_javascript:
  - js/latest.js
plugins:
  - search
markdown_extensions:
  - tables
  - admonition
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mxkvjpknTN
      name: Discord Server
    - icon: fontawesome/brands/github
      link: https://github.com/madeline/docs-v2
      name: Github Repository

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true